AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 100
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  Exclude:
      - test/**/*
      - spec/**/*

Metrics/ModuleLength:
  Exclude:
      - test/**/*
      - spec/**/*

Metrics/ClassLength:
  Exclude:
      - test/**/*
      - spec/**/*

Metrics/BlockLength:
  Exclude:
      - test/**/*
      - spec/**/*
